use std::path::Path;
use std::process::{Command, Stdio};
use super::WallpaperMode;

pub fn set_wallpaper(path: &Path, mode: WallpaperMode) -> Result<String, String> {
    if !path.exists() {
        return Err(format!("File does not exist: {}", path.display()));
    }

    let sway_mode = mode.to_swaybg_mode();

    // 1. Terminate previously running swaybg instance so they do not pile up
    let _ = Command::new("pkill")
        .arg("-x")
        .arg("swaybg")
        .output();

    // 2. Spawn swaybg detached
    let abs_path = if path.is_absolute() {
        path.to_path_buf()
    } else {
        std::env::current_dir().unwrap_or_default().join(path)
    };

    let spawn_res = Command::new("swaybg")
        .arg("-i")
        .arg(&abs_path)
        .arg("-m")
        .arg(sway_mode)
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn();

    match spawn_res {
        Ok(_) => {
            // Save startup script for Sway / Hyprland autostart
            save_autostart_script(&abs_path, sway_mode);
            Ok(format!("Wallpaper set with swaybg ({})", mode.as_str()))
        }
        Err(e) => {
            Err(format!(
                "Failed to execute 'swaybg -i \"{}\" -m {}': {}. Please ensure swaybg is installed.",
                abs_path.display(),
                sway_mode,
                e
            ))
        }
    }
}

fn save_autostart_script(path: &Path, mode: &str) {
    if let Some(home) = std::env::var_os("HOME") {
        let config_dir = Path::new(&home).join(".config").join("swaybg");
        let _ = std::fs::create_dir_all(&config_dir);
        let script_path = config_dir.join("current_wallpaper.sh");
        let script_content = format!(
            "#!/bin/sh\n# Generated by PaperLite Wallpaper Manager\npkill -x swaybg 2>/dev/null\nswaybg -i \"{}\" -m {} &\n",
            path.display(),
            mode
        );
        let _ = std::fs::write(&script_path, script_content);

        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let _ = std::fs::set_permissions(&script_path, std::fs::Permissions::from_mode(0o755));
        }
    }
}
